//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.18444
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CF11.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("admin")]
        public string account {
            get {
                return ((string)(this["account"]));
            }
            set {
                this["account"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("123")]
        public string password {
            get {
                return ((string)(this["password"]));
            }
            set {
                this["password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11.2")]
        public double sgs_drl_L_led1_x {
            get {
                return ((double)(this["sgs_drl_L_led1_x"]));
            }
            set {
                this["sgs_drl_L_led1_x"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9.47")]
        public double sgs_drl_L_led1_y {
            get {
                return ((double)(this["sgs_drl_L_led1_y"]));
            }
            set {
                this["sgs_drl_L_led1_y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("22.28")]
        public double sgs_drl_L_led2_x {
            get {
                return ((double)(this["sgs_drl_L_led2_x"]));
            }
            set {
                this["sgs_drl_L_led2_x"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20.59")]
        public double sgs_drl_L_led2_y {
            get {
                return ((double)(this["sgs_drl_L_led2_y"]));
            }
            set {
                this["sgs_drl_L_led2_y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11.2")]
        public double sgs_drl_R_led1_x {
            get {
                return ((double)(this["sgs_drl_R_led1_x"]));
            }
            set {
                this["sgs_drl_R_led1_x"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9.47")]
        public double sgs_drl_R_led1_y {
            get {
                return ((double)(this["sgs_drl_R_led1_y"]));
            }
            set {
                this["sgs_drl_R_led1_y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("22.28")]
        public double sgs_drl_R_led2_x {
            get {
                return ((double)(this["sgs_drl_R_led2_x"]));
            }
            set {
                this["sgs_drl_R_led2_x"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20.59")]
        public double sgs_drl_R_led2_y {
            get {
                return ((double)(this["sgs_drl_R_led2_y"]));
            }
            set {
                this["sgs_drl_R_led2_y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double sgs_low_power_L_led1_x {
            get {
                return ((double)(this["sgs_low_power_L_led1_x"]));
            }
            set {
                this["sgs_low_power_L_led1_x"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double sgs_low_power_L_led1_y {
            get {
                return ((double)(this["sgs_low_power_L_led1_y"]));
            }
            set {
                this["sgs_low_power_L_led1_y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double sgs_low_power_L_led2_x {
            get {
                return ((double)(this["sgs_low_power_L_led2_x"]));
            }
            set {
                this["sgs_low_power_L_led2_x"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double sgs_low_power_L_led2_y {
            get {
                return ((double)(this["sgs_low_power_L_led2_y"]));
            }
            set {
                this["sgs_low_power_L_led2_y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double sgs_low_power_R_led1_x {
            get {
                return ((double)(this["sgs_low_power_R_led1_x"]));
            }
            set {
                this["sgs_low_power_R_led1_x"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double sgs_low_power_R_led1_y {
            get {
                return ((double)(this["sgs_low_power_R_led1_y"]));
            }
            set {
                this["sgs_low_power_R_led1_y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double sgs_low_power_R_led2_x {
            get {
                return ((double)(this["sgs_low_power_R_led2_x"]));
            }
            set {
                this["sgs_low_power_R_led2_x"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double sgs_low_power_R_led2_y {
            get {
                return ((double)(this["sgs_low_power_R_led2_y"]));
            }
            set {
                this["sgs_low_power_R_led2_y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11.28")]
        public double sgs_vave_L_led1_x {
            get {
                return ((double)(this["sgs_vave_L_led1_x"]));
            }
            set {
                this["sgs_vave_L_led1_x"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9.08")]
        public double sgs_vave_L_led1_y {
            get {
                return ((double)(this["sgs_vave_L_led1_y"]));
            }
            set {
                this["sgs_vave_L_led1_y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("21.97")]
        public double sgs_vave_L_led2_x {
            get {
                return ((double)(this["sgs_vave_L_led2_x"]));
            }
            set {
                this["sgs_vave_L_led2_x"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20.68")]
        public double sgs_vave_L_led2_y {
            get {
                return ((double)(this["sgs_vave_L_led2_y"]));
            }
            set {
                this["sgs_vave_L_led2_y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11.08")]
        public double sgs_vave_R_led1_x {
            get {
                return ((double)(this["sgs_vave_R_led1_x"]));
            }
            set {
                this["sgs_vave_R_led1_x"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9.08")]
        public double sgs_vave_R_led1_y {
            get {
                return ((double)(this["sgs_vave_R_led1_y"]));
            }
            set {
                this["sgs_vave_R_led1_y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("21.97")]
        public double sgs_vave_R_led2_x {
            get {
                return ((double)(this["sgs_vave_R_led2_x"]));
            }
            set {
                this["sgs_vave_R_led2_x"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20.68")]
        public double sgs_vave_R_led2_y {
            get {
                return ((double)(this["sgs_vave_R_led2_y"]));
            }
            set {
                this["sgs_vave_R_led2_y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double first_offset {
            get {
                return ((double)(this["first_offset"]));
            }
            set {
                this["first_offset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.25")]
        public double second_offset {
            get {
                return ((double)(this["second_offset"]));
            }
            set {
                this["second_offset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double sgs_drl_L_ydir {
            get {
                return ((double)(this["sgs_drl_L_ydir"]));
            }
            set {
                this["sgs_drl_L_ydir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public double sgs_drl_R_ydir {
            get {
                return ((double)(this["sgs_drl_R_ydir"]));
            }
            set {
                this["sgs_drl_R_ydir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double sgs_low_power_L_ydir {
            get {
                return ((double)(this["sgs_low_power_L_ydir"]));
            }
            set {
                this["sgs_low_power_L_ydir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public double sgs_low_power_R_ydir {
            get {
                return ((double)(this["sgs_low_power_R_ydir"]));
            }
            set {
                this["sgs_low_power_R_ydir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double sgs_vave_L_ydir {
            get {
                return ((double)(this["sgs_vave_L_ydir"]));
            }
            set {
                this["sgs_vave_L_ydir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public double sgs_vave_R_ydir {
            get {
                return ((double)(this["sgs_vave_R_ydir"]));
            }
            set {
                this["sgs_vave_R_ydir"] = value;
            }
        }
    }
}
